-- 코드를 입력하세요
SELECT  B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE * C.SALES) AS TOTAL_SALES
FROM    BOOK AS A, AUTHOR AS B, BOOK_SALES AS C
WHERE   A.BOOK_ID = C.BOOK_ID
AND     A.AUTHOR_ID = B.AUTHOR_ID
AND     DATE_FORMAT(C.SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY
ORDER BY B.AUTHOR_ID ASC, A.CATEGORY DESC
