-- 코드를 작성해주세요
WITH RECURSIVE GENERATION_TBL AS (
    SELECT  ID, PARENT_ID, 1 AS 'GENERATION'
    FROM    ECOLI_DATA
    WHERE   PARENT_ID IS NULL
    UNION ALL
    SELECT  A.ID, A.PARENT_ID, B.GENERATION + 1
    FROM    ECOLI_DATA AS A INNER JOIN GENERATION_TBL AS B
        ON  A.PARENT_ID = B.ID
)

SELECT   ID
FROM     GENERATION_TBL
WHERE    GENERATION = 3
ORDER BY ID ASC;