-- 코드를 작성해주세요
SELECT  A.ITEM_ID, B.ITEM_NAME, B.RARITY
FROM    ITEM_TREE AS A, ITEM_INFO AS B
WHERE   A.ITEM_ID = B.ITEM_ID   
AND     A.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID AS ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_ID DESC
