-- 코드를 작성해주세요
WITH CHILD_CNT_TBL AS (
SELECT   PARENT_ID AS ID, COUNT(PARENT_ID) AS CHILD_COUNT
FROM     ECOLI_DATA
WHERE    PARENT_ID IS NOT NULL
GROUP BY PARENT_ID)

SELECT  ID, 
        CASE
            WHEN CHILD_COUNT IS NULL THEN 0
            ELSE CHILD_COUNT
        END AS 'CHILD_COUNT'
FROM(
SELECT  A.ID, CHILD_COUNT
FROM    ECOLI_DATA AS A LEFT JOIN CHILD_CNT_TBL AS B
ON   A.ID = B.ID) AS Z
ORDER BY ID
