-- 코드를 입력하세요
SELECT  PRODUCT_CODE,
        MAX(P.PRICE) * SUM(F.SALES_AMOUNT) AS SALES
FROM    OFFLINE_SALE AS F LEFT JOIN PRODUCT AS P
    USING (PRODUCT_ID)
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;

