-- 코드를 입력하세요
SELECT  FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM    REST_INFO
WHERE   (FOOD_TYPE, FAVORITES) IN (
    SELECT  FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM    REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC
-- 음식종류별로 즐겨찾기수가 가장 많은 식당의 음식종류, ID, 식당이름, 즐겨찾기수