-- 코드를 작성해주세요

SELECT  ID, EMAIL, FIRST_NAME, LAST_NAME
FROM    DEVELOPER_INFOS 
WHERE   UPPER(SKILL_1) = 'PYTHON' OR 
        UPPER(SKILL_2) = 'PYTHON' OR 
        UPPER(SKILL_3) = 'PYTHON' 
ORDER BY ID ASC