-- 코드를 작성해주세요

SELECT    COUNT(ID) AS 'FISH_COUNT',
          MAX(N.FISH_NAME) AS 'FISH_NAME'
FROM      FISH_INFO AS I INNER JOIN FISH_NAME_INFO AS N
    USING (FISH_TYPE)
GROUP BY  I.FISH_TYPE
ORDER BY  FISH_COUNT DESC;