-- 코드를 입력하세요

WITH ONLINE_SALE_WITH_USER_INFO AS (
    SELECT  YEAR(O.SALES_DATE) AS YEAR,
            MONTH(O.SALES_DATE) AS MONTH,
            COUNT(DISTINCT O.USER_ID) AS SALES_CNT
    FROM    ONLINE_SALE AS O INNER JOIN USER_INFO AS U
        USING (USER_ID)
    WHERE   YEAR(U.JOINED) = 2021
    GROUP BY 1, 2 
),

TOTAL_CNT_2021 AS (
    SELECT COUNT(USER_ID) AS TOTAL_CNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT A.YEAR, A.MONTH, A.SALES_CNT AS PUCHASED_USERS, ROUND(A.SALES_CNT/B.TOTAL_CNT, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE_WITH_USER_INFO AS A , TOTAL_CNT_2021 AS B 
ORDER BY YEAR ASC, MONTH ASC
