-- 코드를 작성해주세요
WITH RECURSIVE GENERATION_TBL AS(
    SELECT  ID, PARENT_ID, 1 AS GENERATION
    FROM    ECOLI_DATA
    WHERE   PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT  E.ID, E.PARENT_ID, G.GENERATION + 1
    FROM    ECOLI_DATA AS E INNER JOIN GENERATION_TBL AS G
        ON  E.PARENT_ID = G.ID
)

SELECT   COUNT(G.GENERATION) AS 'COUNT', G.GENERATION
FROM     ( SELECT   ID, PARENT_ID
           FROM     ECOLI_DATA
           WHERE    ID NOT IN 
                    (SELECT PARENT_ID
                     FROM   GENERATION_TBL
                     WHERE  PARENT_ID IS NOT NULL)) AS E
           INNER JOIN
           GENERATION_TBL AS G
        ON E.ID = G.ID
GROUP   BY G.GENERATION
ORDER   BY G.GENERATION ASC

