-- 코드를 입력하세요
-- FOOD_PRODUCT와 FOOD_ORDER 테이블에서 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회하는 SQL문을
SELECT   O.PRODUCT_ID,
         P.PRODUCT_NAME, 
         P.PRICE * SUM(O.AMOUNT) AS TOTAL_SALES
FROM     FOOD_ORDER AS O INNER JOIN FOOD_PRODUCT AS P 
WHERE    O.PRODUCT_ID = P.PRODUCT_ID
    AND  DATE_FORMAT(O.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY O.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC