# -- 코드를 입력하세요

WITH RENTAL_DURATION_TBL AS (
SELECT B.HISTORY_ID,
       B.CAR_ID,
       TIMESTAMPDIFF(DAY, B.START_DATE, B.END_DATE) + 1 AS 'RENTAL_DURATION',
       CASE
        WHEN
             TIMESTAMPDIFF(DAY, B.START_DATE, B.END_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN
             TIMESTAMPDIFF(DAY, B.START_DATE, B.END_DATE) + 1 >= 30  THEN '30일 이상'
        WHEN
             TIMESTAMPDIFF(DAY, B.START_DATE, B.END_DATE) + 1 >= 7 THEN '7일 이상'
        ELSE 
            '할인 없음'
        END AS 'DURATION_TYPE'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY  AS B 
)


SELECT Z.HISTORY_ID, 
       CASE
        WHEN Z.DURATION_TYPE = '할인 없음' THEN Z.DAILY_FEE * Z.RENTAL_DURATION
        ELSE 
             ROUND((Z.DAILY_FEE * (100 - PLAN.DISCOUNT_RATE) / 100 ) * Z.RENTAL_DURATION, 0)
        END AS FEE
FROM (
SELECT  B.HISTORY_ID, A.CAR_ID, A.CAR_TYPE,A.DAILY_FEE, B.RENTAL_DURATION, B.DURATION_TYPE
FROM    CAR_RENTAL_COMPANY_CAR AS A,
        RENTAL_DURATION_TBL AS B
WHERE   A.CAR_ID = B.CAR_ID
AND     A.CAR_TYPE = '트럭') AS Z 
        LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
        ON Z.CAR_TYPE = PLAN.CAR_TYPE
        AND Z.DURATION_TYPE = PLAN.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC
        
# SELECT DATE('2022-10-15') - DATE('2022-09-16')

# SELECT TIMESTAMPDIFF(DAY,'2022-09-16','2022-10-15')


-- 자동차 종류가 '트럭'인 자동차의 대여 기록
-- 대여 기록 별로 대여 금액을 구하여 대여 기록 id 와 대여 금액 리스트를 출력하는 SQL문
-- 대여 금액 기준 내림차순, 기록 ID 기준 내림차순