-- 코드를 입력하세요
-- 7월 아이스크림 총 주문량과 상반기 아이스크림 총 주문량을 더한 값이 큰순으로 상위 3개 맛 조회
SELECT  FLAVOR
FROM(
    SELECT      FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM        FIRST_HALF
    GROUP BY    FLAVOR
    UNION ALL   
    SELECT      FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM        JULY
    GROUP BY    FLAVOR
) AS Z
GROUP BY    FLAVOR
ORDER BY    SUM(TOTAL_ORDER) DESC
LIMIT  3
