WITH RECURSIVE CLOCK_HOUR AS (
    SELECT  0 AS HOUR
    UNION ALL
    SELECT  HOUR + 1
    FROM    CLOCK_HOUR
    WHERE   HOUR < 23
)

-- 코드를 입력하세요
SELECT   A.HOUR, COUNT(DATETIME) AS 'COUNT'
FROM     CLOCK_HOUR AS A LEFT OUTER JOIN ANIMAL_OUTS AS B 
      ON A.HOUR = HOUR(B.DATETIME) 
GROUP BY A.HOUR
ORDER BY HOUR ASC