-- 코드를 입력하세요
WITH RECURSIVE TIME_TBL AS (
    SELECT  9 AS HOUR
    UNION ALL
    SELECT HOUR + 1 
    FROM   TIME_TBL
    WHERE  HOUR < 19
)


SELECT   T.HOUR,
         IFNULL(COUNT(A.ANIMAL_ID),0) AS COUNT
FROM     TIME_TBL AS T LEFT JOIN ANIMAL_OUTS AS A
    ON   T.HOUR = HOUR(A.DATETIME)
GROUP BY T.HOUR
ORDER BY HOUR ASC