-- 코드를 작성해주세요
SELECT  ID, GENOTYPE, PARENT_GENOTYPE
FROM(
SELECT  A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE
FROM    ECOLI_DATA AS A, ECOLI_DATA AS B
WHERE   A.PARENT_ID = B.ID
) AS Z
WHERE   (GENOTYPE & PARENT_GENOTYPE) = PARENT_GENOTYPE
ORDER BY ID ASC