-- 코드를 입력하세요
WITH    UPPER5_RENT_CAR_ID_TBL AS(
    SELECT   CAR_ID 
    FROM     CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE    START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING   COUNT(CAR_ID) >= 5
)

SELECT   MONTH(START_DATE) AS MONTH,
         CAR_ID,
         COUNT(*) AS RECORDS
FROM     CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE    CAR_ID IN (SELECT CAR_ID FROM UPPER5_RENT_CAR_ID_TBL)
AND      START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY CAR_ID, MONTH
HAVING   RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC;