-- 코드를 작성해주세요
WITH MAX_LEN_PER_FISH_TYPE AS (
SELECT   A.FISH_TYPE, MAX(A.LENGTH) AS LENGTH
FROM     FISH_INFO AS A 
GROUP BY A.FISH_TYPE
)

SELECT   A.ID, B.FISH_NAME, A.LENGTH
FROM     FISH_INFO A LEFT JOIN FISH_NAME_INFO B
    ON   A.FISH_TYPE = B.FISH_TYPE
WHERE    (A.FISH_TYPE, A.LENGTH) IN (SELECT * FROM MAX_LEN_PER_FISH_TYPE)
ORDER BY A.ID ASC

