-- 코드를 입력하세요
SELECT  GOODS.TITLE, 
        GOODS.BOARD_ID,
        REPLY.REPLY_ID,
        REPLY.WRITER_ID,
        REPLY.CONTENTS,
        DATE_FORMAT(REPLY.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM    USED_GOODS_BOARD AS GOODS, USED_GOODS_REPLY AS REPLY
WHERE   GOODS.CREATED_DATE BETWEEN '2022-10-01' and '2022-10-31'
AND     (GOODS.BOARD_ID = REPLY.BOARD_ID)
ORDER BY REPLY.CREATED_DATE ASC, GOODS.TITLE ASC