-- 코드를 입력하세요
SELECT  GOODS.BOARD_ID,
        GOODS.WRITER_ID,
        GOODS.TITLE,
        GOODS.PRICE,
        CASE
            WHEN GOODS.STATUS = 'SALE' THEN '판매중'
            WHEN GOODS.STATUS = 'RESERVED' THEN '예약중'
            WHEN GOODS.STATUS = 'DONE' THEN '거래완료'
        END AS STATUS
FROM    USED_GOODS_BOARD AS GOODS
WHERE CREATED_DATE = '2022-10-05'
ORDER BY GOODS.BOARD_ID DESC